version: "3.4"

services:
  web:
    image: codeforacause/podsticarijum-app:#{TAG_NUMBER}#
    container_name: podsticarijum-api
    ports:
      - "23000:80"
    environment:
      - ConnectionStrings__PodsticarijumDb=#{DB_CONNECTION_STRING}#
      - MailData__Password=#{MAIL_DATA_PASSWORD}#
      - MailData__AppMailAddressFrom=podsticarijum@gmail.com
      - MailData__Host=smtp.gmail.com
      - MailData__Port=587
    restart: always
