version: "3.4"

services:
  web:
    image: codeforacause/podsticarijum-app:#{TAG_NUMBER}#
    container_name: podsticarijum-api
    ports:
      - "23000:80"
    environment:
      - ConnectionStrings__PodsticarijumDb=Server=db;Database=podsticarijum;User Id=sa;Password=SecurePass12345;
      - ASPNETCORE_ENVIRONMENT=Production
      - MailData__Password=uiydwxfnhxjqpdzf
      - MailData__AppMailAddressFrom=podsticarijum@gmail.com
      - MailData__Host=smtp.gmail.com
      - MailData__Port=587
    restart: always
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: podsticarijum-db
    ports:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SecurePass12345
    volumes:
      - ".:/app:rw"
    restart: always
