version: "3.4"

services:
  web:
    image: codeforacause/podsticarijum-app:#{TAG_NUMBER}#
    container_name: podsticarijum-api
    ports:
      - "23000:80"
      - "23001:443"
    environment:
      - ConnectionStrings__PodsticarijumDb=Server=db;Database=podsticarijum;User Id=sa;Password=#{DB_PASSWORD}#;
      - ASPNETCORE_ENVIRONMENT=Production
      - MailData__Password=#{MAIL_DATA_PASSWORD}#
      - MailData__AppMailAddressFrom=podsticarijum@gmail.com
      - MailData__Host=smtp.gmail.com
      - MailData__Port=587
      - DB_PASSWORD=#{DB_PASSWORD}#
    restart: always
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: podsticarijum-db
    ports:
      - "23456:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=#{DB_PASSWORD}#
    volumes:
      # First do this on the server:
      # mkdir data && sudo chown 10001 data
      - "./data:/var/opt/mssql:rw"
    restart: always
