version: "3.4"

services:
  web:
    image: codeforacause/podsticarijum-app:#{TAG_NUMBER}#
    container_name: podsticarijum-api
    ports:
      - "23000:80"
    environment:
      - ASPNETCORE_MailData__Password=#{MAIL_DATA_PASSWORD}#
      - ASPNETCORE_MailData__AppMailAddressFrom=podsticarijum@gmail.com
      - ASPNETCORE_MailData__Host=smtp.gmail.com
      - ASPNETCORE_MailData__Port=587
